### ISSUE TITLE
cannot remove projects

### ISSUE THREAD

**Issue by WladyX** [Infisical/infisical#1120]
With the latest helm 0.4.1 and latests image 0.40.2, if i try to remove a project i see in the UI:
```
Failed to delete project
```

in the logs i get:
```
2023-10-25T15:25:55.686Z [IFSC:backend-main] error: MongoTransactionError: Cannot call commitTransaction after calling abortTransaction
    at endTransaction (/backend/node_modules/mongodb/lib/sessions.js:442:22)
    at node:internal/util:364:7
    at new Promise (<anonymous>)
    at endTransaction (node:internal/util:350:12)
    at ClientSession.commitTransaction (/backend/node_modules/mongodb/lib/sessions.js:270:16)
    at /backend/build/helpers/workspace.js:224:27
    at Generator.next (<anonymous>)
    at fulfilled (/backend/build/helpers/workspace.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
The server encountered an error while processing the request
```

**Comment by imrefazekas** [comment]
I have the same issue. Project can not be deleted. Same error.

**Comment by Shraeyas** [comment]
Can I work on this issue?

**Comment by maidul98** [comment]
@WladyX This is related to our move to using transactions on MongoDB. We are actively looking into this and will provide more details here as we further uncover the issue

**Comment by WladyX** [comment]
Thanks for the update, appreciate it.

**Comment by Shraeyas** [comment]
@maidul98 I tried to setup mongo instance with a replica set locally and this issue does not pop up.

I wanted to understand what's the expectation here. I should be able to make a PR with updated docker files to setup mongo locally with replica sets if thats what we are looking for.

**Comment by maidul98** [comment]
@Shraeyas Yes, if you can make a PR to add replica set for docker compose, that would be great

**Comment by Shraeyas** [comment]
@maidul98 I had a few observations related to error handling while deleting projects and have created a PR (#1142 ) for that.

Will have a look into the mongodb replica set as well.
