### ISSUE TITLE
[ENG-214] can not set secrets of folders

### ISSUE THREAD

**Issue by imrefazekas** [Infisical/infisical#1136]
### Describe the bug

System does not allow to set secrets inside folders.

### To Reproduce

use latest docker image.
Create a folder inside a project. Add a secret (for dev). Save it. Try to save a value in another environment (for prod)-

### Error in logs

```
2023-10-28 21:32:45 2023-10-28T19:32:45.641Z [IFSC:backend-main] error: Error: Invalid path. Folders not found
2023-10-28 21:32:45     at /backend/build/services/FolderService.js:202:19
2023-10-28 21:32:45     at Generator.next (<anonymous>)
2023-10-28 21:32:45     at fulfilled (/backend/build/services/FolderService.js:5:58)
2023-10-28 21:32:45     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-10-28 21:32:45 The server encountered an error while processing the request
```

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-214](https://linear.app/infisical/issue/ENG-214/can-not-set-secrets-of-folders)</sub>

**Comment by akhilmhdh** [comment]
Hey @imrefazekas this should be fixed in our recent release. Closing as its resolved
