### ISSUE TITLE
db-migration error

### ISSUE THREAD

**Issue by baek-sang** [Infisical/infisical#1511]
### Describe the bug
postgresql variables not working

### To Reproduce
1. https://infisical.com/docs/self-hosting/deployment-options/docker-compose

```
$ cat .env
...
# Postgres creds
POSTGRES_PASSWORD=password-123
POSTGRES_USER=user-name-123
POSTGRES_DB=infisical
...
```
```
docker logs infisical-db-migration

> backend@1.0.0 migration:latest
> knex --knexfile ./src/db/knexfile.ts --client pg migrate:latest

Requiring external module ts-node/register
Working directory changed to /backend/src/db
[dotenv@16.4.1][DEBUG] No encoding is specified. UTF-8 is used by default
[dotenv@16.4.1][DEBUG] Failed to load /.env.migration ENOENT: no such file or directory, open '/.env.migration'
[dotenv@16.4.1][DEBUG] No encoding is specified. UTF-8 is used by default
[dotenv@16.4.1][DEBUG] Failed to load /.env ENOENT: no such file or directory, open '/.env'
Using environment: production
password authentication failed for user "infisical"
error: password authentication failed for user "infisical"
    at Parser.parseErrorMessage (/backend/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/backend/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/backend/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
npm notice
npm notice New minor version of npm available! 10.2.4 -> 10.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
npm notice Run `npm install -g npm@10.5.0` to update!
npm notice
```

### Expected behavior
no error

### Platform you are having the issue on:
- fedora 39
- docker 25.0.3

**Comment by akhilmhdh** [comment]
@baek-sang you have edited the postgres password and user. These env as used by postgres image.

Now make sure you reflect the same change in `DB_CONNECTION_URI` the one used by infisical. The is update the URI to reflect the infisical changes.

Closing this issue as its a user error
