### ISSUE TITLE
Email isn't send using https self-hosted

### ISSUE THREAD

**Issue by levx-me** [Infisical/infisical#1633]
### Describe the bug
Email isn't send using https self-hosted

### To Reproduce
1. Go to 'Account Control'
2. Click on 'Add Member'
3. Type in email address
```
B86C4EE42E7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
```

### Expected behavior
An email should be sent

### Screenshots
<img width="324" alt="Screenshot 2024-03-28 at 4 49 32 AM" src="https://github.com/Infisical/infisical/assets/69745700/bf20f190-a72f-45bd-b5b5-4875166032e2">

### Platform you are having the issue on:
Fedora 39

### Additional context
I set up self hosted using docker-compose and I'm accessing it through https using nginx config like:
TSL certificate was issued using certbot by letsencrypt and I'm bypassing request to 8001 which docker-compose is run at.

```
server {
        listen 443 ssl;
        server_name infisical.my.domain;

        ssl_certificate /etc/letsencrypt/live/infisical.my.domain/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/infisical.my.domain/privkey.pem;

        proxy_redirect      off;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    Host $http_host;

        location / {
            proxy_pass http://localhost:8001/;
            proxy_buffering off;
            proxy_buffer_size 16k;
            proxy_busy_buffers_size 24k;
            proxy_buffers 64 4k;
        }
    }
```

**Comment by akhilmhdh** [comment]
Which email service are you using

**Comment by levx-me** [comment]
both gmail and resend doesn't work

**Comment by maidul98** [comment]
@levx-me are you able to try Sendgrid?

**Comment by mtracz** [comment]
I faced the same issue when upgrading from `infisical/infisical:v0.43.16` to `infisical/infisical:v0.51.9-postgres` self-hosted.
Gmail SMTP stopped working.

based on infisical's SMTP docs:
https://github.com/Infisical/infisical/blob/246e6c64d1e26f69a0ba8e006a329d8a2c11e919/docs/self-hosting/configuration/envars.mdx?plain=1#L212-L228

---
not work:
```
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE="true"
```

works (port 465):
```
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_SECURE="true"
```

works (secure false):
```
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE="false"
```

Regarding to node mailer docs, which is used in Infisical (https://github.com/Infisical/infisical/blob/main/backend/package.json#L113)

https://www.nodemailer.com/smtp/

> secure – if true the connection will use TLS when connecting to server. If false (the default) then TLS is used if server supports the STARTTLS extension. In most cases set this value to true if you are connecting to port 465. For port 587 or 25 keep it false

I think Infisical docs should be adjusted.

**Comment by tafaust** [comment]
Hey, I'd like to follow up on this issue. We have Google Workspace accounts and cannot get SMTP to work in Infisical with our Google Workspace Gmail accounts.
The only configuration that made it work halfway, is:
```
SMTP_HOST         = "smtp.gmail.com"
SMTP_PORT         = 465
SMTP_IGNORE_TLS   = "true"
SMTP_REQUIRE_TLS  = "false"
SMTP_USERNAME.    = "this@address.com"
SMTP_FROM_ADDRESS = "other@address.com"
```

At startup, I see
> Testing smtp connection
> SMTP successfully connected

in the logs but as soon as I try to send an Email via Infisical, I receive the following error:
> {"level":50,"time":1725099572402,"pid":1,"hostname":"infisical","reqId":"req-a","severity":"ERROR","err":{"type":"Error","message":"Mail command failed: 530-5.7.0 Must issue a STARTTLS command first. For more information, go to\n530-5.7.0  https://support.google.com/a/answer/3221692 and review RFC 3207\n530 5.7.0 specifications. a640c23a62f3a-a89891db022sm313303766b.146 - gsmtp","stack":"Error: Mail command failed: 530-5.7.0 Must issue a STARTTLS command first. For more information, go to\n530-5.7.0  https://support.google.com/a/answer/3221692 and review RFC 3207\n530 5.7.0 specifications. a640c23a62f3a-a89891db022sm313303766b.146 - gsmtp\n    at SMTPConnection._formatError (/backend/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n    at SMTPConnection._actionMAIL (/backend/node_modules/nodemailer/lib/smtp-connection/index.js:1594:34)\n    at SMTPConnection.<anonymous> (/backend/node_modules/nodemailer/lib/smtp-connection/index.js:1063:18)\n    at SMTPConnection._processResponse (/backend/node_modules/nodemailer/lib/smtp-connection/index.js:969:20)\n    at SMTPConnection._onData (/backend/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)\n    at SMTPConnection._onSocketData (/backend/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","code":"EENVELOPE","response":"530-5.7.0 Must issue a STARTTLS command first. For more information, go to\n530-5.7.0  https://support.google.com/a/answer/3221692 and review RFC 3207\n530 5.7.0 specifications. a640c23a62f3a-a89891db022sm313303766b.146 - gsmtp","responseCode":530,"command":"MAIL FROM"},"msg":"Mail command failed: 530-5.7.0 Must issue a STARTTLS command first. For more information, go to\n530-5.7.0  https://support.google.com/a/answer/3221692 and review RFC 3207\n530 5.7.0 specifications. a640c23a62f3a-a89891db022sm313303766b.146 - gsmtp"}

**Comment by tafaust** [comment]
FYI we've built a Terraform / OpenTOFU module collection to provision docker resource (meant to be for Docker Swarm). Here is the Infisical implementation https://github.com/ehwplus/terraswarm/tree/main/modules/infisical in case you want to mention it in your docs.
