### ISSUE TITLE
Migration from mongodb to postgresql fails with cryptic error

### ISSUE THREAD

**Issue by mpsOxygen** [Infisical/infisical#1727]
### Describe the bug
I am following this guide in order to migrate from mongodb to postgresql, on prem: https://infisical.com/docs/self-hosting/guides/mongo-to-postgres

### To Reproduce
Follow guide:
1. git clone -b infisical/v0.46.11-postgres https://github.com/Infisical/infisical.git
2. cd backend
3. npm install
4. cd ../pg-migrator
5.   npm install
6.   npm run migration

This is the output from npm run migration:
```
[root@fedora-debug pg-migrator]# npm run migration

> pg-migrator@1.0.0 migration
> tsx src/index.ts

Type the mongodb url: mongodb://infisical:mypassword@mongodb:27017/infisical
Checking mongoose connection...
Connected successfully to mongo
Type the postgres url: postgresql://infisical:mypassword@postgres-infisical-cluster-rw:5432/infisical
Checking postgres connection...
Connected successfully to postgres
Starting rolling back to latest, comment this out later
Rolling back completed
Executing migration
Completed migration
Starting migration of  User  Postgres table name: users
Total documents 9
Total batches 1
Batch No.: 1
Finished migration of  User  Postgres table name: users
Starting migration of  User  Postgres table name: user_encryption_keys
Total documents 9
Total batches 1
Batch No.: 1
Finished migration of  User  Postgres table name: user_encryption_keys
Starting migration of  BackupPrivateKey  Postgres table name: backup_private_key
Total documents 9
Total batches 1
Batch No.: 1
Finished migration of  BackupPrivateKey  Postgres table name: backup_private_key
Starting migration of  Organization  Postgres table name: organizations
Total documents 1
Total batches 1
Batch No.: 1
Finished migration of  Organization  Postgres table name: organizations
Starting migration of  Role  Postgres table name: org_roles
Total documents 0
Total batches 0
Finished migration of  Role  Postgres table name: org_roles
Starting migration of  MembershipOrg  Postgres table name: org_memberships
Total documents 8
Total batches 1
Batch No.: 1
Finished migration of  MembershipOrg  Postgres table name: org_memberships
Starting migration of  IncidentContactOrg  Postgres table name: incident_contacts
Total documents 0
Total batches 0
Finished migration of  IncidentContactOrg  Postgres table name: incident_contacts
Starting migration of  UserAction  Postgres table name: user_actions
Total documents 13
Total batches 1
Batch No.: 1
Finished migration of  UserAction  Postgres table name: user_actions
Starting migration of  ServerConfig  Postgres table name: super_admin
Total documents 2
Total batches 1
Batch No.: 1
error: insert into "super_admin" ("allowSignUp", "createdAt", "id", "initialized", "updatedAt") values ($1, $2, $3, $4, $5), ($6, $7, $8, $9, $10) returning "id" - duplicate key value violates unique constraint "super_admin_pkey"
    at Parser.parseErrorMessage (/root/infisical/pg-migrator/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/root/infisical/pg-migrator/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/root/infisical/pg-migrator/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/root/infisical/pg-migrator/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 233,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(00000000-0000-0000-0000-000000000000) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'super_admin',
  column: undefined,
  dataType: undefined,
  constraint: 'super_admin_pkey',
  file: 'nbtinsert.c',
  line: '666',
  routine: '_bt_check_unique'
}

```

### Expected behavior
I expected the migration to work.

### Platform you are having the issue on:
Kubernetes

**Comment by akhilmhdh** [comment]
@mpsOxygen did you already created the super admin in your postgres instance AWS. If so kindly take a fresh postgres instance without any data before migrating

**Comment by mpsOxygen** [comment]
> @mpsOxygen did you already created the super admin in your postgres instance? If so kindly take a fresh postgres instance without any data before migrating

No, it gave the error with fresh database. The problem was the fact that we had 2 admin level accounts in infisical. We deleted one and it worked after that.

**Comment by maidul98** [comment]
@mpsOxygen are you unblocked at the moment?

**Comment by mpsOxygen** [comment]
Yes, the workaround unblocked us, but I do have an outstanding PR related to the helm chart [here](https://github.com/Infisical/infisical/pull/1766).

**Comment by akhilmhdh** [comment]
Closing as stale
