### ISSUE TITLE
Integration Vercel  400 error on self-hosted infisical

### ISSUE THREAD

**Issue by shelbon** [Infisical/infisical#1880]
### Describe the bug
On self hosted infisical
### To Reproduce
 1 - create the integration 
 2 -  set Redirect url like so https://your-domain.com/integrations/vercel/oauth2/callback
 3 - set the environment variable :
        CLIENT_ID_VERCEL: The Client (Integration) ID of your Vercel integration.
        CLIENT_SECRET_VERCEL: The Client (Integration) Secret of your Vercel integration.
        CLIENT_SLUG_VERCEL: The URL Slug of your Vercel integration.
  4 - restart the infiscal instance
  5 - add vercel integration 
### Expected behavior
vercel integration sucessfully addedd
### Screenshots
![Screenshot from 2024-05-27 14-08-08](https://github.com/Infisical/infisical/assets/20593460/f7a4d7c5-725d-4609-bb49-fce4b466088c)

**Comment by shelbon** [comment]
yes `{"level":50,"time":1716969461411,"pid":1,"hostname":"c24210b548c8","reqId":"req-1eb","severity":"ERROR","err":{"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (file:///backend/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///backend/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at IncomingMessage.emit (node:domain:488:12)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (file:///backend/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async exchangeCodeVercel (file:///backend/dist/services/integration-auth/integration-token.mjs:82:16)\n    at async Object.oauthExchange (file:///backend/dist/services/integration-auth/integration-auth-service.mjs:51:27)\n    at async Object.handler (file:///backend/dist/server/routes/v1/integration-auth-router.mjs:214:31)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded;charset=utf-8","User-Agent":"axios/1.6.7","Content-Length":"174","Accept-Encoding":"gzip, compress, deflate, br"},"method":"post","url":"https://api.vercel.com/v2/oauth/access_token","data":"code=9X0Lu2nbILaAVqXJfThMn85h&client_id=oac_cFIjVQdwD8i7xacBygnauHIF&client_secret=ucNZqKdF01y29FKOXqO8zdwg&redirect_uri=undefined%2Fintegrations%2Fvercel%2Foauth2%2Fcallback","axios-retry":{"retries":3,"shouldResetTimeout":false,"retryCount":0,"lastRequestTime":1716969460847}},"code":"ERR_BAD_REQUEST","status":400},"msg":"Request failed with status code 400"}
{"level":50,"time":1716969461412,"pid":1,"hostname":"c24210b548c8","reqId":"req-1eb","severity":"ERROR","req":{"method":"POST","url":"/api/v1/integration-auth/oauth-token","hostname":"vault.pydweb.xyz","remoteAddress":"83.142.147.16","remotePort":34744},"res":{"statusCode":500},"err":{"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (file:///backend/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///backend/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:531:35)\n    at IncomingMessage.emit (node:domain:488:12)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (file:///backend/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async exchangeCodeVercel (file:///backend/dist/services/integration-auth/integration-token.mjs:82:16)\n    at async Object.oauthExchange (file:///backend/dist/services/integration-auth/integration-auth-service.mjs:51:27)\n    at async Object.handler (file:///backend/dist/server/routes/v1/integration-auth-router.mjs:214:31)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/x-www-form-urlencoded;charset=utf-8","User-Agent":"axios/1.6.7","Content-Length":"174","Accept-Encoding":"gzip, compress, deflate, br"},"method":"post","url":"https://api.vercel.com/v2/oauth/access_token","data":"code=9X0Lu2nbILaAVqXJfThMn85h&client_id=oac_cFIjVQdwD8i7xacBygnauHIF&client_secret=ucNZqKdF01y29FKOXqO8zdwg&redirect_uri=undefined%2Fintegrations%2Fvercel%2Foauth2%2Fcallback","axios-retry":{"retries":3,"shouldResetTimeout":false,"retryCount":0,"lastRequestTime":1716969460847}},"code":"ERR_BAD_REQUEST","status":400},"msg":"Request failed with status code 400"}
{"level":30,"time":1716969461414,"pid":1,"hostname":"c24210b548c8","reqId":"req-1eb","severity":"INFO","res":{"statusCode":500},"responseTime":892.5502640008926,"msg":"request completed"}`

**Comment by MadEngineX** [comment]
@shelbon try to set `SITE_URL`

https://github.com/Infisical/infisical/blob/main/.env.example#L24C1-L24C9

**Comment by akhilmhdh** [comment]
Closing this issue as vercel integration have been converted to new secret sync infra and this should be fixed as well.

Reference doc: https://infisical.com/docs/integrations/secret-syncs/vercel
