### ISSUE TITLE
If I use the Secret API, WorkspaceSlug will not be able to find the Secret.

### ISSUE THREAD

**Issue by myeong-han** [Infisical/infisical#1894]
### Bug description
When using the `GET /v3/secrets/raw` API, we found a problem where the secret could be found using workspaceId, but the project could not be found using workspaceSlug.

### To reproduce
1. Check project ID and slug
```bash
auth=mytoken
projectid=c9bd15a4-7295-4a4d-89ab-e66d0df63844
endpoint=myselfhost
curl --request GET \
 --url ${endpoint}/api/v1/workspace/${projectid} \
 --header "Authorization: Bearer ${auth}" | jq
```
>stdout
```stdout
 % Total % Received % Xferd Average Speed ​​Time Time Time Current
 Dload Upload Total Spent Left Speed
100 582 100 582 0 0 13706 0 --:--:-- --:--:-- --:--:-- 13857
{
 "workspace": {
 "id": "c9bd15a4-7295-4a4d-89ab-e66d0df63844",
 "name": "infra",
 "slug": "infra-3-ke-j",
 "autoCapitalization": true,
 "orgId": "800b0b42-81a9-441d-a6f9-fa8cf7a489a8",
 "createdAt": "2024-05-24T06:36:19.989Z",
 "updatedAt": "2024-05-24T06:36:19.989Z",
 "version": 2,
 "upgradeStatus": null,
 "_id": "c9bd15a4-7295-4a4d-89ab-e66d0df63844",
 "environments": [
 {
 "name": "Development",
 "slug": "dev",
 "id": "ed29a407-3a6d-4f5a-8560-bb74a06bef87"
 },
 {
 "name": "Staging",
 "slug": "staging",
 "id": "43c2a586-952b-4f1c-af12-48d2a8e62219"
 },
 {
 "name": "Production",
 "slug": "prod",
 "id": "bb278f63-969c-4241-b4ab-f430cee96db1"
 }
 ]
 }
}
```
2. Call secret API using projectID
```bash
auth=mytoken
workspaceId=c9bd15a4-7295-4a4d-89ab-e66d0df63844
environment=dev
recursive=true
secretPath=%2Ftest1
endpoint=myselfhost
curl --request GET \
 --url "${endpoint}/api/v3/secrets/raw?workspaceId=${workspaceId}&environment=${environment}&recursive=${recursive}&secretPath=${secretPath}" \
 --header "Authorization: Bearer ${auth}" | jq
```
>stdout
```stdout
 % Total % Received % Xferd Average Speed ​​Time Time Time Current
 Dload Upload Total Spent Left Speed
100 273 100 273 0 0 6146 0 --:--:-- --:--:-- --:--:-- 6204
{
 "secrets": [
 {
 "id": "4ec6b337-0d92-4b18-9e1f-585396dfd8f9",
 "_id": "4ec6b337-0d92-4b18-9e1f-585396dfd8f9",
 "workspace": "c9bd15a4-7295-4a4d-89ab-e66d0df63844",
 "environment": "dev",
 "version": 1,
 "type": "shared",
 "secretKey": "AAA",
 "secretValue": "bbb",
 "secretComment": ""
 }
 ],
 "imports": []
}
```
3. Call secret API using projectSlug
```bash
mhkim@fredric:~/playgrounds-fredric/iac/1.manifests/cicd$ auth=mytoken
workspaceSlug=infra-3-ke-j
environment=dev
recursive=true
secretPath=%2Ftest1 #"/" = %2F
endpoint=myselfhost
curl --request GET \
 --url "${endpoint}/api/v3/secrets/raw?workspaceSlug=${workspaceSlug}&environment=${environment}&recursive=${recursive}&secretPath=${secretPath}" \
 --header "Authorization: Bearer ${auth}" | jq
```
>stdout
```stdout
 % Total % Received % Xferd Average Speed ​​Time Time Time Current
 Dload Upload Total Spent Left Speed
100 87 100 87 0 0 2603 0 --:--:-- --:--:-- --:--:-- 2558
{
 "statusCode": 400,
 "message": "Missing workspace id or environment",
 "error": "BadRequest"
}
```

### Expected behavior
I expected that actions 2 and 3 would have the same result, but I couldn't find the project.

### screenshot
If applicable, please add screenshots to help explain the issue.

### Platforms experiencing issue:
self-host infisical based on k3s (v1.28.6+k3s2)

### Additional context
I guess I must have misunderstood something. please tell me about it

**Comment by maidul98** [comment]
What version of Infisical are you self hosting?

**Comment by myeong-han** [comment]
I worked with an infisical-standalone Helm chart. Chart version is 1.0.8,
The image used is infisical/infisical:v0.46.3-postgres
The appVersion confirmed in Chart.yaml is 1.0.1.

**Comment by ReaperMaga** [comment]
I got the same error on the latest version.
It does not work even in the k8s operator:

```
{"level":50,"time":1717212611867,"pid":1,"hostname":"infisical-68c9877d56-st54r","reqId":"req-1a4","severity":"ERROR","err":{"type":"BadRequestError","message":"Missing workspace id or environment","stack":"BadRequest: Missing workspace id or environment\n    at Object.handler (file:///backend/dist/server/routes/v3/secret-router.mjs:69:15)\n    at preHandlerCallback (/backend/node_modules/fastify/lib/handleRequest.js:137:37)\n    at validationCompleted (/backend/node_modules/fastify/lib/handleRequest.js:121:5)\n    at preValidationCallback (/backend/node_modules/fastify/lib/handleRequest.js:98:5)\n    at handler (/backend/node_modules/fastify/lib/handleRequest.js:75:7)\n    at handleRequest (/backend/node_modules/fastify/lib/handleRequest.js:24:5)\n    at runPreParsing (/backend/node_modules/fastify/lib/route.js:609:5)\n    at next (/backend/node_modules/fastify/lib/hooks.js:233:9)\n    at handleResolve (/backend/node_modules/fastify/lib/hooks.js:250:7)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"BadRequest"},"msg":"Missing workspace id or environment"}
```

**Comment by maidul98** [comment]
@myeong-han  Workspace slug was introduced in later versions of Infisical. Please update your Infisical instance to a newer version so that it works with the API call you are making

**Comment by myeong-han** [comment]
@maidul98 thank you. i'll try it
