### ISSUE TITLE
Failed to create admin Infisical Standalone Kubernetes

### ISSUE THREAD

**Issue by wefersmasasana** [Infisical/infisical#1992]
I installed Infisical Standalone with the helm chart and added the infisical-secrets, my pods are running fine. After I connect with the Service the "Welcome to Infisical" register page comes up. After I filled out the Input fields and press on the "Continue" button, this error came up: "Failed to create admin". I checked the logs of the Infisical Standalone Pod in Kubernetes and found this: 

"ERROR","err":{"type":"BadRequestError","message":"User already exist","stack":"Admin sign up: User already exist\n    at Object.adminSignUp (file:///backend/dist/services/super-admin/super-admin-service.mjs:32:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.handler (file:///backend/dist/server/routes/v1/admin-router.mjs:97:45)","name":"Admin sign up"},"msg":"User already exist"}

After I sawed this message I tried to use other credentials and changed for example the email address, but this didn't helped.

**Comment by maidul98** [comment]
What version version of Infisical are you on?

**Comment by ezradibiase** [comment]
Hi all,

I'm, experiencing the same problem.

Installed from cloned repository, in this way:
helm upgrade --install infisical infisical/infisical-standalone -f values.yaml

Kubernetes Server Version: v1.29.2
chart version: 1.0.8
appVersion: "1.0.1"
dependencies:
  - name: ingress-nginx
    version: 4.0.13
  - name: postgresql
    version: 14.1.3
    tag: "v0.46.3-postgres"
  - name: redis
    version: 18.14.0

Thank you in advance.
