### ISSUE TITLE
Trouble upgrading from 0.77.3 to 0.86.1 and restoring database dump

### ISSUE THREAD

**Issue by nenadfilipovic** [Infisical/infisical#2487]
### Describe the bug

I have trouble upgrading my service to latest version, I am testing it locally by pulling same version that I keep on cloud and by fetching and applying database backup from s3. It works until I restart infisical service, then it gets into restart loop and shows this error inside logs

```
{"level":30,"time":1727337410860,"pid":1,"hostname":"2476a74093b8","severity":"INFO","msg":"KMS: Encrypted ROOT Key found from DB. Decrypting."}
{"level":50,"time":1727337410860,"pid":1,"hostname":"2476a74093b8","severity":"ERROR","err":{"type":"Error","message":"Unsupported state or unable to authenticate data","stack":"Error: Unsupported state or unable to authenticate data\n    at Decipheriv.final (node:internal/crypto/cipher:193:29)\n    at Object.decrypt (/backend/src/lib/crypto/cipher/cipher.ts:41:75)\n    at Object.startService (/backend/src/services/kms/kms-service.ts:799:39)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async registerRoutes (/backend/src/server/routes/index.ts:1195:3)"},"msg":"Unsupported state or unable to authenticate data"}
```

### To Reproduce

- Pull old version (docker-compose up -d, my docker compose is pretty much the same as .prod one in main branch)
- Run migrations (same setup as above, its run automatically)
- Trigger database restore (pg_restore custom service I use)

**Comment by nenadfilipovic** [comment]
I had to use same encryption key as on cloud...
