### ISSUE TITLE
Envkey migration does not work

### ISSUE THREAD

**Issue by trungklam** [Infisical/infisical#2648]
### Describe the bug
Follow the documentation, I'm migrating my EnvKey (selfhost) to Infisical (selfhost) but it didn't work.

### To Reproduce
Follow the docs here https://infisical.com/docs/documentation/guides/migrating-from-envkey

### Expected behavior
The data from Envkey migrate to Infisical successfully

### Screenshots
I got the error email 😄 
![image](https://github.com/user-attachments/assets/e4324bac-dd04-48e1-abbe-145ab3b83ee6)

### Additional context
Having look to the logs, I found the error seems related to how Infisical parse the data from Envkey and turn it into SQL query. It's specifically locate in `project_environments` , so probably some cases was not covered there but I didn't manage to figure it out.
Any help will be much appreciated ! Thank you 😃 

`{""severity":"ERROR","err":{"type":"DatabaseError","message":"Failed to execute db ops","stack":"Create: Failed to execute db ops
at Object.create (/backend/src/lib/knex/index.ts:129:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async <anonymous> (/backend/src/services/external-migration/external-migration-fns.ts:172:21)
at async <anonymous> (/backend/src/lib/knex/index.ts:74:19)","name":"Create","error":{"type":"DatabaseError","message":"insert into \"project_environments\" (\"name\", \"position\", \"projectId\", \"slug\") values (DEFAULT, $1, $2, $3) returning * - null value in column \"name\" of relation \"project_environments\" violates not-null constraint","stack":"error: insert into \"project_environments\" (\"name\", \"position\", \"projectId\", \"slug\") values (DEFAULT, $1, $2, $3) returning * - null value in column \"name\" of relation \"project_environments\" violates not-null constraint
at Parser.parseErrorMessage (/backend/node_modules/pg-protocol/src/parser.ts:369:69)
at Parser.handlePacket (/backend/node_modules/pg-protocol/src/parser.ts:188:21)
at Parser.parse (/backend/node_modules/pg-protocol/src/parser.ts:103:30)
at TLSSocket.<anonymous> (/backend/node_modules/pg-protocol/src/index.ts:7:48)
at TLSSocket.emit (node:events:519:28)
at TLSSocket.emit (node:domain:488:12)
at addChunk (node:internal/streams/readable:559:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
at Readable.push (node:internal/streams/readable:390:5)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)","length":377,"name":"error","severity":"ERROR","code":"23502","detail":"Failing row contains (a976b7dd-0304-4445-bd2d-ceba753f288d, null, undefined-h7ra, 1, dc3e7a24-3ae8-4083-9f16-b1723df6d889, 2024-10-26 11:30:23.691403+00, 2024-10-26 11:30:23.691403+00).","schema":"public","table":"project_environments","column":"name","file":"execMain.c","line":"1889","routine":"ExecConstraints"}},"msg":"Failed to import data from external source"}
`

**Comment by trungklam** [comment]
This issue was solved with the release v0.92.0-posgres
