### ISSUE TITLE
Infisical helm chart deployment fails. (self hosted)

### ISSUE THREAD

**Issue by wooarchi** [Infisical/infisical#2733]
### Describe the bug
I tried deploying Infisical helm chart.  However, it was not distributed properly.
- helm chart info
```
name: infisical-standalone
type: application
version: 1.4.0
```

- infisical image version
  - v0.93.1-postgres

### To Reproduce

- helm repo add
```
$ helm repo add infisical-helm-charts 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/' 
$ helm repo update
```

- create namespace
```
$ kubectl create namespace infisical
```

- deploy infisical-secrets.yaml
```
$ cat <<EOF > infisical-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  AUTH_SECRET: $(openssl rand -hex 16)
  ENCRYPTION_KEY: $(openssl rand -base64 32)
  SITE_URL: https://infisical.exmaple.com
EOF

$ kubectl apply -f infisical-secrets.yaml
```

- helm deploy
```
$ helm upgrade --install infisical infisical-helm-charts/infisical-standalone -n infisical
```

### Expected behavior
- pod status
```
NAME                                                        READY   STATUS             RESTARTS      AGE
infisical-infisical-standalone-infisical-7796b4474c-prrnc   0/1     CrashLoopBackOff   3 (17s ago)   2m10s
infisical-schema-migration-1-pjl22                          0/1     Completed          3             2m10s
postgresql-0                                                1/1     Running            0             2m10s
redis-master-0                                              1/1     Running            0             2m10s
```

- pod logs
```
$ kubectl logs -n infisical pod/infisical-infisical-standalone-infisical-7796b4474c-prrnc
Defaulted container "infisical-standalone-infisical" out of: infisical-standalone-infisical, migration-init (init)
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
Telemetry is enabled
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":30,"time":1731572792351,"pid":1,"hostname":"infisical-infisical-standalone-infisical-7796b4474c-prrnc","severity":"INFO","msg":"KMS: Generating ROOT Key"}
{"level":50,"time":1731572792351,"pid":1,"hostname":"infisical-infisical-standalone-infisical-7796b4474c-prrnc","severity":"ERROR","err":{"type":"RangeError","message":"Invalid key length","stack":"RangeError: Invalid key length\n    at Cipheriv.createCipherBase (node:internal/crypto/cipher:121:19)\n    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:140:3)\n    at new Cipheriv (node:internal/crypto/cipher:243:3)\n    at Object.createCipheriv (node:crypto:147:10)\n    at Object.encrypt (/backend/src/lib/crypto/cipher/cipher.ts:19:27)\n    at Object.startService (/backend/src/services/kms/kms-service.ts:830:37)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async registerRoutes (/backend/src/server/routes/index.ts:1260:3)","code":"ERR_CRYPTO_INVALID_KEYLEN"},"msg":"Invalid key length"}
```

- secret info
```
$ kubectl get secrets -n infisical infisical-secrets -oyaml
apiVersion: v1
data:
  AUTH_SECRET: YzhiMzQ5Njk2OGU2ODNmNjA2NzA1MDNhOGIwY2I2MTY=
  ENCRYPTION_KEY: dnJ6K1VuNzNwU3RrYS92cVpkakE1MmZMNUVOdUExNjcwdWgzdHZaVjV3Zz0=
  SITE_URL: aHR0cHM6Ly9pbmZpc2ljYWwuY2hhbmdoby5vcmc=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"infisical-secrets","namespace":"infisical"},"stringData":{"AUTH_SECRET":"c8b3496968e683f60670503a8b0cb616","ENCRYPTION_KEY":"vrz+Un73pStka/vqZdjA52fL5ENuA1670uh3tvZV5wg=","SITE_URL":"https://infisical.changho.org"},"type":"Opaque"}
  creationTimestamp: "2024-11-14T06:55:55Z"
  name: infisical-secrets
  namespace: infisical
  resourceVersion: "5538374"
  uid: 9a604c24-d2f9-4876-aad7-6768260395d6
type: Opaque
```
### Additional context
If there is anything I missed, please let me know.

**Comment by wooarchi** [comment]
I confirmed it was a simple mistake on my part.
- update
```
$ cat <<EOF > infisical-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  AUTH_SECRET: $(openssl rand -base64 32)
  ENCRYPTION_KEY: $(openssl rand -hex 16)
  SITE_URL: https://infisical.exmaple.com
EOF

$ kubectl apply -f infisical-secrets.yaml
```
