### ISSUE TITLE
Fail to "Resend invite" because "Access denied to one or more of the specified projects"

### ISSUE THREAD

**Issue by jizusun** [Infisical/infisical#2889]
### To Reproduce
1. Go to 'Organization access control'
2. Click on 'Resend invite'
3. The UI says  "Access denied to one or more of the specified projects"
4. The screenshot is attached later, and here is the log
```sh
infisical-backend       | {"level":30,"time":1734427577974,"pid":1,"hostname":"bb4841472728","reqId":"req-7LAwUmfgn1C3dh","severity":"INFO","req":{"method":"GET","url":"/images/loading/loading.gif","hostname":"pww-infisical-130-147-249-243.traefik.me","remoteAddress":"161.92.168.122","remotePort":43514},"msg":"incoming request"}
infisical-backend       | {"level":30,"time":1734427577977,"pid":1,"hostname":"bb4841472728","reqId":"req-PB6CvRRWIfrIDg","severity":"INFO","req":{"method":"POST","url":"/api/v1/invite-org/signup","hostname":"pww-infisical-130-147-249-243.traefik.me","remoteAddress":"161.92.168.122","remotePort":19014},"msg":"incoming request"}
infisical-backend       | {"level":30,"time":1734427577981,"pid":1,"hostname":"bb4841472728","reqId":"req-7LAwUmfgn1C3dh","severity":"INFO","res":{"statusCode":304},"responseTime":6.5930633544921875,"msg":"request completed"}
infisical-backend       | {"level":30,"time":1734427577983,"pid":1,"hostname":"bb4841472728","reqId":"req-PB6CvRRWIfrIDg","severity":"INFO","msg":"injectPermission: Injecting permissions for [permissionsForIdentity=b047d203-24d4-4c11-a399-8c72cc7f56c2] [type=user]"}
infisical-backend       | {"level":30,"time":1734427577983,"pid":1,"hostname":"bb4841472728","reqId":"req-PB6CvRRWIfrIDg","severity":"INFO","msg":"getPlan: attempting to fetch plan for [orgId=36837e48-cfe9-43b8-8abf-36ed33340a07] [projectId=undefined]"}
infisical-backend       | {"level":30,"time":1734427577991,"pid":1,"hostname":"bb4841472728","reqId":"req-PB6CvRRWIfrIDg","severity":"INFO","msg":"getPlan: attempting to fetch plan for [orgId=36837e48-cfe9-43b8-8abf-36ed33340a07] [projectId=undefined]"}
infisical-backend       | {"level":50,"time":1734427577991,"pid":1,"hostname":"bb4841472728","reqId":"req-PB6CvRRWIfrIDg","severity":"ERROR","err":{"type":"ForbiddenRequestError","message":"Access denied to one or more of the specified projects","stack":"ForbiddenError: Access denied to one or more of the specified projects\n    at Object.inviteUserToOrganization (/backend/src/services/org/org-service.ts:559:13)\n    at async Object.handler (/backend/src/server/routes/v1/invite-org-router.ts:48:53)","name":"ForbiddenError"},"msg":"Access denied to one or more of the specified projects"}
infisical-backend       | {"level":30,"time":1734427577992,"pid":1,"hostname":"bb4841472728","reqId":"req-PB6CvRRWIfrIDg","severity":"INFO","res":{"statusCode":403},"responseTime":15.01025390625,"msg":"request completed"}
```

### Expected behavior
Should resend invite

### Screenshots
![image](https://github.com/user-attachments/assets/97b46222-fa89-463f-9ec5-304ed93c29a3)

![image](https://github.com/user-attachments/assets/fabc04e0-214c-4475-8194-b8c6e96817bc)

### Platform you are having the issue on:
Version: v0.98.0-postgres

**Comment by Raman-79** [comment]
@jizusun, do you want the already generated link to be sent or a fresh one?

**Comment by gee-forr** [comment]
I'm having the same problem as @jizusun.

For myself - I want to send a fresh invite, because the 24-hour invite timeout has lapsed.

I am assuming that the `Resend Invite` button sends a fresh invite link that will last for another 24 hours? Is this assumption correct? If it's not, is there another way to send a fresh invite after the first one expires?

**Comment by SkylarWolfLA** [comment]
We are also experiencing this issue (migrated from Envkey).

To solve it we had to delete the user and re-invite them.

**Comment by akhilmhdh** [comment]
This has been fixed in #3001 and will be deployed soon

**Comment by bartvdbraak** [comment]
We're running into this issue as well.
