### ISSUE TITLE
Unable to use infisical in production .net core with infisical sdk

### ISSUE THREAD

**Issue by stratusaxarlis** [Infisical/infisical#2913]
It fails to start any project in any environent , linux , windows 
in .net 9
### To Reproduce
1. Go to  your cproj add 	<PackageReference Include="Infisical.Sdk" Version="2.3.7" />
2. as described in the documentation login using the following:
 ` ClientSettings settings = new()
 {
     SiteUrl = "https://eu.infisical.com/",
     Auth = new Infisical.Sdk.AuthenticationOptions
     {
         UniversalAuth = new UniversalAuthMethod
         {
             ClientId = "clientid",
             ClientSecret = "clientsecret         }
     }
 };
 var secretsClient = new InfisicalClient(settings);`

3. build for production 
4. deploy in any server
5 You will get the following error : 
6. See error
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'infisical_c' or one of its dependencies: The specified module could not be found. (0x8007007E)
at Infisical.Sdk.InfisicalLibrary.init(String settings)
at Infisical.Sdk.InfisicalLibrary.Init(String settings)
at Infisical.Sdk.InfisicalClient..ctor(ClientSettings settings)

### Expected behavior
it should work in publish release but it doesnt it copies the dll in the project folder but it cannot reference it as it seems 

### Platform you are having the issue on:
windows server , windows 11, any OS

**Comment by Albatz6** [comment]
I'm currently facing the same error when trying to deploy an app using Docker on arm64 and it looks like switching to a non-Alpine image helps. 

There's also a very similar issue in the sdk repo [here](https://github.com/Infisical/sdk/issues/53).

**Comment by gcscript** [comment]
same problem here

**Comment by oamm** [comment]
I'm currently facing the same issue, and it's difficult to resolve since the SDK source code is not available. I hope the maintainers can either fix the problem or make the code public again.
