### ISSUE TITLE
GitLab Integration Support for Self-Hosted GitLab

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#418]
### Feature description
Currently, Infisical has 2 integration options for GitLab documented further [here](https://infisical.com/docs/integrations/cicd/gitlab):

- Standard (direct connection from Infisical to GitLab Cloud via their API).
- Pipeline (CLI in GitLab pipeline pulls secrets from Infisical; works for GitLab Cloud and Self-Hosted).

The Standard option only works for sending secrets to GitLab Cloud but users may be self-hosting GitLab on their own infrastructure.

What's needed is a modification to the Standard option to be able to sync secrets from Infisical to GitLab Self-Hosted.

### Why would it be useful?
Users self-hosting GitLab would appreciate being able to use the Standard option.

### Additional context
This may or may not be complicated because you have to account for:

1. Authentication with GitLab Self-Hosted (the one currently for GitLab Cloud authenticates via OAuth2 but not sure how it is structured for the self-hosted option).
2. Record URL/pointer to your GitLab Self-Hosted instance.

**Comment by franckffv** [comment]
Hello @maidul98 

I'm following up on this issue for modifying the Standard option to support syncing secrets from Infisical to **GitLab Self-Hosted**. Are there any updates on this feature? Will it be included in your upcoming roadmap?

Thanks in advance for your response.

**Comment by beliven-daniele-sarnari** [comment]
Support here, do we have any idea about when this feature will be release? Thanks

**Comment by Salman2301** [comment]
Will look into this.

**Comment by WladyX** [comment]
This is already released, we have been using it for some time already.
https://infisical.com/docs/integrations/cicd/gitlab - see the **Self-Hosted Setup** tab

**Comment by Salman2301** [comment]
@WladyX 
I believe, we need a way to add Gitlab Self-Hosted URL.
As there is no way to config. "Self-Hosted Setup tab" is for Infisical Self-Hosted setup.

**Comment by beliven-daniele-sarnari** [comment]
> I have both, Infisical selfhosted and gitlab selfhosted. When you go to integrations in the infisical UI under gitlab you can add the selfhosted url, like in the screenshot: ![CleanShot 2024-02-29 at 17 15 12@2x](https://private-user-images.githubusercontent.com/1106868/308974275-5d286cbb-db2e-4ee6-99d0-12838cba42b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjAxMjYsIm5iZiI6MTcwOTIxOTgyNiwicGF0aCI6Ii8xMTA2ODY4LzMwODk3NDI3NS01ZDI4NmNiYi1kYjJlLTRlZTYtOTlkMC0xMjgzOGNiYTQyYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMTUxNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTcxNzNmMDQ0YjdlN2U0ZTNlNWQwYjkzZjZkMTBiOGNjZjQyNzZkNDIzNjkzM2NmNGIwYjkyOTljYjkyYTg4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vl-b85Xzh2XGxG-Uyrt2G4kssiFYY9QzEYpnllXSg40)

i have the same form too, but when i try to connect with my Gitlab CE tenant:
![image](https://github.com/Infisical/infisical/assets/131280766/e8fa77c9-47b8-43ce-b762-b4304db75b5e)

**Comment by WladyX** [comment]
```
Back in your Infisical instance, add two new environment variables for the credentials of your GitLab application:

CLIENT_ID_GITLAB: The Client ID of your GitLab application.
CLIENT_SECRET_GITLAB: The Secret of your GitLab application.
Once added, restart your Infisical instance and use the GitLab integration.
```

Have you done this? As per the docs?

**Comment by beliven-daniele-sarnari** [comment]
> ```
> Back in your Infisical instance, add two new environment variables for the credentials of your GitLab application:
> 
> CLIENT_ID_GITLAB: The Client ID of your GitLab application.
> CLIENT_SECRET_GITLAB: The Secret of your GitLab application.
> Once added, restart your Infisical instance and use the GitLab integration.
> ```
> 
> Have you done this? As per the docs?

That's required only in Self hosted instance of Infisical
`Using the GitLab integration on a self-hosted instance of Infisical requires configuring an application in GitLab and registering your instance with it.`

I am on Infisical Cloud + Gitlab CE

**Comment by Salman2301** [comment]
It make sense, why this is not working? The self-hosted URL and the  CLIENT_ID/CLIENT_SECRET in the Infisical cloud are not the same. Since this is issue related only to Infisical cloud. I think someone from the core team, should take a look.

**Comment by beliven-daniele-sarnari** [comment]
@maidul98 can we mark this as a real issue / bug? what do you think?
Thanks

**Comment by dangtony98** [comment]
Hi folks!

I've just checked the flow and I believe that Infisical Cloud is currently configured specifically to sync to GitLab Cloud.

That said, you can sync to a self-hosted instance of GitLab if you self-host Infisical yourself and configure it appropriately with the right `CLIENT_ID_GITLAB` and `CLIENT_SECRET_GITLAB` as mentioned by @WladyX . We'll definitely look into adding support for syncing from Infisical Cloud to self-hosted GitLab instances at some point soon but in the meantime do feel free to send in PRs for it.

Alternatively, for any enterprises, we'd be happy to provide a dedicated, managed Infisical Cloud instance that is able to sync to your self-hosted GitLab instance. If this is of interest, feel free to drop a line to team@infisical.com.

**Comment by beliven-daniele-sarnari** [comment]
> Hi folks!
> 
> I've just checked the flow and I believe that Infisical Cloud is currently configured specifically to sync to GitLab Cloud.
> 
> That said, you can sync to a self-hosted instance of GitLab if you self-host Infisical yourself and configure it appropriately with the right `CLIENT_ID_GITLAB` and `CLIENT_SECRET_GITLAB` as mentioned by @WladyX . We'll definitely look into adding support for syncing from Infisical Cloud to self-hosted GitLab instances at some point soon but in the meantime do feel free to send in PRs for it.
> 
> Alternatively, for any enterprises, we'd be happy to provide a dedicated, managed Infisical Cloud instance that is able to sync to your self-hosted GitLab instance. If this is of interest, feel free to drop a line to [team@infisical.com](mailto:team@infisical.com).

Ok thanks @dangtony98 for the quick response.

**Comment by atefhaloui** [comment]
Hi,
May be this is the wrong thread but does infisical support glabally available application on gitlab self-hosted instance ? I've created an application from the admin area on gitlab and set the `CLIENT_ID_GITLAB` and `CLIENT_SECRET_GITLAB` accordingly. I've also set the `GITLAB_URL` as an environment variable even if it will be set from the UI.  When I try to complete the gitlab integration after setting `GitLab Integration Type` to `Individual`, there are no projects in the list (no projects found). On the logs side, I can see this error:
```
{"level":50,"time":1709639613858,"pid":1,"hostname":"c43430d439b4","reqId":"req-3o","severity":"ERROR","err":{"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at settle (file:///backend/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///backend/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:530:35)\n    at IncomingMessage.emit (node:domain:488:12)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (file:///backend/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getAppsGitlab (file:///backend/dist/services/integration-auth/integration-app-list.mjs:287:24)\n    at async Object.getIntegrationApps (file:///backend/dist/services/integration-auth/integration-auth-service.mjs:212:18)\n    at async Object.handler (file:///backend/dist/server/routes/v1/integration-auth-router.mjs:258:20)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer e32c0ec286e1b79a17da437f075a252cfc492df25cbe7ffaa3306e60478277c0","Accept-Encoding":"application/json","User-Agent":"axios/1.6.7"},"params":{},"method":"get","url":"https://gitlab.company.com/api/v4/groups/undefined/projects","axios-retry":{"retries":3,"shouldResetTimeout":false,"retryCount":0,"lastRequestTime":1709639613801}},"code":"ERR_BAD_REQUEST","status":404},"msg":"Request failed with status code 404"}
```
if I set `Group` instead of `Individual` the application, It returns 500:
```
Something went wrong. Please contact [support@infisical.com](mailto:support@infisical.com) if the issue persists.
```
and on the logs I have this error:
```
{"level":50,"time":1709639614918,"pid":1,"hostname":"c43430d439b4","reqId":"req-3p","severity":"ERROR","req":{"method":"GET","url":"/api/v1/integration-auth/8c6ea3fe-b4a6-400a-9992-dfdd3bd2d46b/apps?teamId=undefined","hostname":"infisical.company.com","remoteAddress":"161.106.88.17","remotePort":44210},"res":{"statusCode":500},"err":{"message":"Request failed with status code 404","name":"AxiosError","stack":"AxiosError: Request failed with status code 404\n    at settle (file:///backend/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///backend/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:530:35)\n    at IncomingMessage.emit (node:domain:488:12)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (file:///backend/node_modules/axios/lib/core/Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async getAppsGitlab (file:///backend/dist/services/integration-auth/integration-app-list.mjs:287:24)\n    at async Object.getIntegrationApps (file:///backend/dist/services/integration-auth/integration-auth-service.mjs:212:18)\n    at async Object.handler (file:///backend/dist/server/routes/v1/integration-auth-router.mjs:258:20)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer e32c0ec286e1b79a17da437f075a252cfc492df25cbe7ffaa3306e60478277c0","Accept-Encoding":"application/json","User-Agent":"axios/1.6.7"},"params":{},"method":"get","url":"https://gitlab.company.com/api/v4/groups/undefined/projects","axios-retry":{"retries":3,"shouldResetTimeout":false,"retryCount":0,"lastRequestTime":1709639614890}},"code":"ERR_BAD_REQUEST","status":404},"msg":"Request failed with status code 404"}
{"level":30,"time":1709639614918,"pid":1,"hostname":"c43430d439b4","reqId":"req-3p","severity":"INFO","res":{"statusCode":500},"responseTime":34.870799999684095,"msg":"request completed"}
```

Would it be possible to have a unique application instead of registering a per-group or a per-project application ?

Note: I'm using version v0.46.5-postgres.

Thank you.

**Comment by filipproch** [comment]
Encountered the same issue as mentioned by @atefhaloui and the likely culprit is that the backend expects IDs returned from the instance to be Strings but they are integer

https://github.com/Infisical/infisical/blob/635948c4f43f855e344ba0fcc0fb7b5c89ee70d4/backend/src/services/integration-auth/integration-team.ts#L25

I checked and my instance definitely returns an integer (1, 2, 3 ...) for project ID.

And further down the stack there is Zod validation on `teamId` being a string
and since its `optional` I assume it just drops it as its missing in the response the frontend gets

![image](https://github.com/Infisical/infisical/assets/1387116/0cd7c78e-aa8f-4718-8cc6-44ffbc700d55)

@dangtony98 is PR welcome or do you want to fix this yourself?

**Comment by filipproch** [comment]
Actually now I see it - the integration-team puts it as `teamId`
but the Zod schema as `id` - that's why its not included and no validation error
so the bugs are two - the type and the zod schema
which should be `teamId: z.string().optional()`  (maybe remove the optional?)

**Comment by rwarford** [comment]
I am also having this error and created a new issue (https://github.com/Infisical/infisical/issues/1875#issue-2317881687) to make sure this is seen as a distinct bug.

**Comment by karedinvs** [comment]
Hi there
I guess have the same issue. Any updates? Was it fixed?
FYI: gitlab self-hosted and Infisical k8s standalone


Response:
```
HTTP/1.1 400 Bad Request
Server: nginx/1.25.2
Date: Tue, 05 Aug 2025 12:59:22 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 147
Connection: keep-alive
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: same-origin
Origin-Agent-Cluster: ?1
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 0
vary: Origin
access-control-allow-origin: https://gcpsecrets-nonprod.domain.com
access-control-allow-credentials: true
etag: "L0WOwhqIhgqNJS0DK2a4WyYEbyE="
```

Request:

```
POST /api/v1/app-connections/gitlab HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,ru;q=0.7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoTWV0aG9kIjoiZW1haWwiLCJhdXRoVG9rZW5UeXBlIjoiYWNjZXNzVG9rZW4iLCJ1c2VySWQiOiIxOTIwNTIwNC0wZjRhLTQ5MzMtODk5OS1mYzlhYjFjODJjYzEiLCJ0b2tlblZlcnNpb25JZCI6IjVmNzI5ODc4LWVhMGMtNGE1MS05MTZkLTFmYjlkNDQ0MzRjZiIsImFjY2Vzc1ZlcnNpb24iOjEsIm9yZ2FuaXphdGlvbklkIjoiNGRlM2I3Y2UtOWFiYy00ZWY1LWEwNjItMDhiN2YwOTZhZGYyIiwiaWF0IjoxNzU0Mzk4NzYxLCJleHAiOjE3NTUyNjI3NjF9.w89Zn6RLNMmQoeSZ5VRyPmDq32vb6qV2OFLTr7EGuGc
Connection: keep-alive
Content-Length: 149
Content-Type: application/json
Cookie: apt.uid=AP-YFGMCGUNNIFB-2-1754318106020-81275313.0.2.6b933aba-006b-4c12-b4b5-a0ddc2adfcf4; _ga=GA1.1.321848067.1754318106; _ga_0C4M1PWYZ7=GS2.1.s1754320308$o2$g0$t1754320308$j60$l0$h0; _ga_K2SPJK2C73=GS2.1.s1754320308$o2$g0$t1754320308$j60$l0$h0; _ga_T11SF3WXX2=GS2.1.s1754320308$o2$g0$t1754320308$j60$l0$h0; jid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoTWV0aG9kIjoiZW1haWwiLCJhdXRoVG9rZW5UeXBlIjoicmVmcmVzaFRva2VuIiwidXNlcklkIjoiMTkyMDUyMDQtMGY0YS00OTMzLTg5OTktZmM5YWIxYzgyY2MxIiwidG9rZW5WZXJzaW9uSWQiOiI1ZjcyOTg3OC1lYTBjLTRhNTEtOTE2ZC0xZmI5ZDQ0NDM0Y2YiLCJyZWZyZXNoVmVyc2lvbiI6MSwib3JnYW5pemF0aW9uSWQiOiI0ZGUzYjdjZS05YWJjLTRlZjUtYTA2Mi0wOGI3ZjA5NmFkZjIiLCJpYXQiOjE3NTQzMjk5ODYsImV4cCI6MTc2MjEwNTk4Nn0.nYXvOa2f2UgCLpABz_wVbtONKBduGJOWc6KDFA5ka_A; ph_phc_nSin8j5q2zdhpFDI1ETmFNUIuTG4DwKVyIigrY10XiE_posthog=%7B%22distinct_id%22%3A%22infisical-nonprod%40domain.com%22%2C%22%24sesid%22%3A%5B1754334617077%2C%2201987676-0f92-7ddb-9c81-23dc4fcdc99c%22%2C1754334105490%5D%2C%22%24epp%22%3Atrue%2C%22%24initial_person_info%22%3A%7B%22r%22%3A%22%24direct%22%2C%22u%22%3A%22https%3A%2F%2Fgcpsecrets-nonprod.domain.com%2Flogin%22%7D%7D; sessionId=dxM1kjgrziZbc_2vfDZvYRMwXwoIKzke.MqE75LLci6JhQ4VB2XpgJ2Zw3WgKdqLW35%2FbTcc%2Fua4
Host: gcpsecrets-nonprod.domain.com
Origin: https://gcpsecrets-nonprod.domain.com
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
sec-ch-ua: "Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```


```
{
    "reqId": "req-N4Ab6XWnk1zzSi",
    "statusCode": 400,
    "message": "Failed to exchange OAuth code: Request failed with status code 401",
    "error": "BadRequest"
}
```

**Comment by vtmocanu** [comment]
getting the same 401 on selfhosted gitlab, has anyone get it to work?

**Comment by karedinvs** [comment]
> getting the same 401 on selfhosted gitlab, has anyone get it to work?

https://github.com/Infisical/infisical/releases/tag/v0.147.1-nightly-20250816

**Comment by carlosmonastyrski** [comment]
Hi @vtmocanu @karedinvs

We’ve recently fixed an issue affecting OAuth flows with self-hosted GitLab instances, and the fix should be available in our [latest release v0.148.0](https://github.com/Infisical/infisical/releases/tag/v0.148.0).

If you give it a try using the [GitLab app connection](https://infisical.com/docs/integrations/app-connections/gitlab), it should now work as expected. Please let us know if you still run into any issues. We’d be happy to help.

**Comment by karedinvs** [comment]
> Hi @vtmocanu @karedinvs
> 
> We’ve recently fixed an issue affecting OAuth flows with self-hosted GitLab instances, and the fix should be available in our [latest release v0.148.0](https://github.com/Infisical/infisical/releases/tag/v0.148.0).
> 
> If you give it a try using the [GitLab app connection](https://infisical.com/docs/integrations/app-connections/gitlab), it should now work as expected. Please let us know if you still run into any issues. We’d be happy to help.
> 

@carlosmonastyrski I have tested it before using a pre-release, many thanks, happy with that, it works
