### ISSUE TITLE
Registering new user fails when running self-hosted infisical to Render

### ISSUE THREAD

**Issue by zdenekburda** [Infisical/infisical#579]
### Describe the bug

Deploy self-hosted infisical to Render and try to register a new user. You get the following error.

```
May 15 10:14:09 PM  2023-05-15T20:14:09.031Z [IFSC:database] info: Database connection established
May 15 10:14:09 PM  events.js:377
May 15 10:14:09 PM        throw er; // Unhandled 'error' event
May 15 10:14:09 PM        ^
May 15 10:14:09 PM  Error: listen EADDRINUSE: address already in use :::443
May 15 10:14:09 PM      at Server.setupListenHandle [as _listen2] (net.js:1331:16)
May 15 10:14:09 PM      at listenInCluster (net.js:1379:12)
May 15 10:14:09 PM      at Server.listen (net.js:1465:7)
May 15 10:14:09 PM      at Function.listen (/backend/node_modules/express/lib/application.js:635:24)
May 15 10:14:09 PM      at /backend/build/index.js:148:24
May 15 10:14:09 PM      at Generator.next (<anonymous>)
May 15 10:14:09 PM      at fulfilled (/backend/build/index.js:28:58)
May 15 10:14:09 PM      at processTicksAndRejections (internal/process/task_queues.js:95:5)
May 15 10:14:09 PM  Emitted 'error' event on Server instance at:
May 15 10:14:09 PM      at emitErrorNT (net.js:1358:8)
May 15 10:14:09 PM      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
May 15 10:14:09 PM    code: 'EADDRINUSE',
May 15 10:14:09 PM    errno: -98,
May 15 10:14:09 PM    syscall: 'listen',
May 15 10:14:09 PM    address: '::',
May 15 10:14:09 PM    port: 443
May 15 10:14:09 PM  }
May 15 10:14:09 PM  npm
May 15 10:14:09 PM   ERR! code ELIFECYCLE
May 15 10:14:09 PM  npm ERR! errno 1
May 15 10:14:09 PM  npm ERR! infisical-api@1.0.0 start: `node build/index.js`
May 15 10:14:09 PM  npm
May 15 10:14:09 PM  ERR! Exit status 1
May 15 10:14:09 PM  npm ERR!
May 15 10:14:09 PM  npm ERR! Failed at the infisical-api@1.0.0 start script.
May 15 10:14:09 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
May 15 10:14:12 PM  npm
May 15 10:14:12 PM   ERR! A complete log of this run can be found in:
May 15 10:14:12 PM  npm ERR!     /root/.npm/_logs/2023-05-15T20_14_09_422Z-debug.log
May 15 10:14:12 PM  2023-05-15T20:14:12: PM2 log: App [backend:1] exited with code [1] via signal [SIGINT]
```

### To Reproduce
1. Create Infisical instance on Render as per this https://infisical.com/docs/self-hosting/deployment-options/render
2. Create a Mongo instance on Render as per this https://render.com/docs/deploy-mongodb
3. Configure email server (using sendgrid)
4. to to `/signup` page and click register
5. Add email

### Expected behavior
No requests errors and no errors in server logs

### Platform you are having the issue on:
- Render

**Comment by vmatsiiako** [comment]
@zdenekburda is this still happening for you? 

@maidul98 are you aware of this?

**Comment by maidul98** [comment]
@zdenekburda we have an on going discussion with Render about this and we have not yet identified why this started happening. Meanwhile, i reccomend you try https://infisical.com/docs/self-hosting/deployment-options/digital-ocean-marketplace or another deployment method

**Comment by alphasecio** [comment]
This exact issue is seen on Railway too. Created a simple [Dockerfile](https://github.com/alphasecio/infisical) that pulls the latest Infisical image, and used it in a Railway template that provisions Infisical (and a MongoDB instance) with all the necessary env vars. Is there an issue with the Docker image?

**Comment by neo3k** [comment]
Same problem, here.

**Comment by neo3k** [comment]
Same problem, here. Is a problem with the last version.

**Comment by neto210206** [comment]
Parece que você está enfrentando um problema relacionado ao deploy do Infisical em um ambiente auto-hospedado no Render. O erro indicado no log aponta para um problema de endereço e porta já em uso (EADDRINUSE). Isso sugere que a porta 443 já está sendo utilizada por algum processo anterior. Para resolver essa questão, aqui estão algumas etapas que você pode seguir:

1. **Verifique a Porta 443:** Certifique-se de que nenhum outro serviço ou processo esteja usando a porta 443 no mesmo servidor. Você pode usar o comando `netstat -tuln` ou `lsof -i :443` para verificar se a porta está em uso.

2. **Encerre Processos em Uso:** Se você identificar algum processo em execução na porta 443, encerre-o antes de tentar iniciar o Infisical. Você pode usar o comando `kill` seguido pelo número do PID para encerrar um processo específico.

3. **Verifique as Configurações do Infisical:** Verifique se as configurações de porta do Infisical estão corretas e não estão entrando em conflito com outros serviços ou processos. Certifique-se de que não haja nenhum conflito de porta no arquivo de configuração do Infisical.

4. **Verifique as Configurações de Encaminhamento de Porta no Render:** Certifique-se de que as configurações de encaminhamento de porta no Render estão corretas e não estão interferindo com a porta 443.

5. **Reinicie o Serviço:** Após verificar e resolver quaisquer conflitos de porta, tente reiniciar o serviço do Infisical para ver se o problema persiste.

6. **Logs de Depuração Adicionais:** Se o problema persistir, verifique os logs de depuração adicionais para identificar qualquer outra possível causa do erro.

detalhes específicos do seu ambiente e configurações podem afetar a solução para esse problema. Certifique-se de fazer backup de qualquer configuração ou arquivo antes de fazer alterações.
