### ISSUE TITLE
The latest versions are not compatible with DocumentDB

### ISSUE THREAD

**Issue by neo3k** [Infisical/infisical#740]
### Describe the bug
When using the latest versions of Infisical, there is an incompatibility issue with MongoDB 4.0. I have tested it with MongoDB 5.0, and it works correctly. The problem is that DocumentDB does not provide full support for MongoDB 5.0. The Infisical 0.9.1 tag works correctly.

### To Reproduce
1. Deploy the latest version of Infisical with DocumentDB 5.0 or MongoDB 4.0.
2. After deployment, the following error occurs:

```/backend/node_modules/mongodb/lib/cmap/connection.js:231
callback(new error_1.MongoServerError(document));
^
MongoServerError: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'
at Connection.onMessage (/backend/node_modules/mongodb/lib/cmap/connection.js:231:30)
at MessageStream.<anonymous> (/backend/node_modules/mongodb/lib/cmap/connection.js:61:60)
at MessageStream.emit (node:events:513:28)
at MessageStream.emit (node:domain:489:12)
at processIncomingData (/backend/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
at MessageStream._write (/backend/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
at writeOrBuffer (node:internal/streams/writable:391:12)
at _write (node:internal/streams/writable:332:10)
at MessageStream.Writable.write (node:internal/streams/writable:336:10)
at Socket.ondata (node:internal/streams/readable:754:22) {
ok: 0,
code: 14,
codeName: 'TypeMismatch',
[Symbol(errorLabels)]: Set(0) {}
```

### Expected behavior
The expected behavior is for Infisical to work correctly with DocumentDB.

### Screenshots
N/A

### Platform you are having the issue on:
The issue is occurring on Docker standalone.

### Additional context
The issue arises when using the latest versions of Infisical with Mongo 4.0. However, Infisical works correctly with Mongo 5.0. The problem is that DocumentDB does not provide full support for MongoDB 5.0. To reproduce the bug, simply deploy the latest version of Infisical with either DocumentDB 5.0 or MongoDB 4.0.

**Comment by neo3k** [comment]
I wanted to provide an update on this issue. I've recently tested Infisical on AWS with the latest version, and I'm glad to report that it's working flawlessly. The incompatibility issues previously experienced with MongoDB 4.0 / DocumentDB 5.0 appear to have been addressed.

Thank you to the team for the timely resolution.
