### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by tboulis** [Infisical/infisical#929]
### Describe the bug
Cannot add any secret. The web app throws the below error and the "Save changes" button is stuck at loading state
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at t.encodeUTF8 (_app-d292cc363ac5da9d.js:1:1669041)
    at h (_app-d292cc363ac5da9d.js:1:553693)
    at [env]-1752c26bdb3e9854.js:1:53719
    at [env]-1752c26bdb3e9854.js:1:54678
    at main-5ec97f4390710bd2.js:1:106339
    at Object.next (main-5ec97f4390710bd2.js:1:106444)
    at n (_app-d292cc363ac5da9d.js:1:1851486)
    at s (_app-d292cc363ac5da9d.js:1:1851689)
    at _app-d292cc363ac5da9d.js:1:1851748
    at new Promise (<anonymous>)
t.encodeUTF8 @ _app-d292cc363ac5da9d.js:1
h @ _app-d292cc363ac5da9d.js:1
(anonymous) @ [env]-1752c26bdb3e9854.js:1
(anonymous) @ [env]-1752c26bdb3e9854.js:1
(anonymous) @ main-5ec97f4390710bd2.js:1
(anonymous) @ main-5ec97f4390710bd2.js:1
n @ _app-d292cc363ac5da9d.js:1
s @ _app-d292cc363ac5da9d.js:1
(anonymous) @ _app-d292cc363ac5da9d.js:1
(anonymous) @ _app-d292cc363ac5da9d.js:1
(anonymous) @ [env]-1752c26bdb3e9854.js:1
(anonymous) @ _app-d292cc363ac5da9d.js:1
await in (anonymous) (async)
$e @ framework-79bce4a3a540b080.js:1
Ye @ framework-79bce4a3a540b080.js:1
(anonymous) @ framework-79bce4a3a540b080.js:1
Nr @ framework-79bce4a3a540b080.js:1
Tr @ framework-79bce4a3a540b080.js:1
(anonymous) @ framework-79bce4a3a540b080.js:1
Ie @ framework-79bce4a3a540b080.js:1
(anonymous) @ framework-79bce4a3a540b080.js:1
Fr @ framework-79bce4a3a540b080.js:1
Jt @ framework-79bce4a3a540b080.js:1
Zt @ framework-79bce4a3a540b080.js:1
t.unstable_runWithPriority @ framework-79bce4a3a540b080.js:1
Ql @ framework-79bce4a3a540b080.js:1
Me @ framework-79bce4a3a540b080.js:1
Xt @ framework-79bce4a3a540b080.js:1
```

### To Reproduce
1. Go to Project => Secrets => Select env => Add secrets
2. Add secret Name and value
3. Click "Save Changes"
4. See error in the console

### Expected behavior
It should add the secrets successfully

### Screenshots
![image](https://github.com/Infisical/infisical/assets/24255041/adb32d11-dfa9-4d11-97cf-c4450aed7500)

### Platform you are having the issue on:
Self-hosted `latest` tag deployed yesterday

### Additional context
We tested with another user and the behaviour is the same

**Comment by maidul98** [comment]
Can you add secrets to a different folder?

**Comment by akhilmhdh** [comment]
Closing this as it's fixed in our new secret architecture which doesn't rely on private keys anymore, rather it's based of the new KMS based architecture
